!include "localization\en-US\installer.nsh"
!include "localization\es-ES\installer.nsh"
!include "localization\gl-ES\installer.nsh"
!include "localization\zh-CN\installer.nsh"
!include "localization\sk-SK\installer.nsh"
!include "localization\ru-RU\installer.nsh"
!include "localization\fr-FR\installer.nsh"
!include "localization\pl-PL\installer.nsh"
