// Do not edit this file! It is automatically generated!

#include "en_US/strings.h"
#include "fr_FR/strings.h"
#include "pl_PL/strings.h"
#include "pt_BR/strings.h"
#include "sk_SK/strings.h"
#include "ru_RU/strings.h"
#include "zh_CN/strings.h"
#include "zh_TW/strings.h"
#include "it_IT/strings.h"
#include "de_DE/strings.h"
#include "es_ES/strings.h"
#include "gl_ES/strings.h"
#include "ca_ES/strings.h"
#include "ko_KR/strings.h"

struct strings *languages[] = {
  &en_US,
  &fr_FR,
  &pl_PL,
  &pt_BR,
  &sk_SK,
  &ru_RU,
  &zh_CN,
  &zh_TW,
  &it_IT,
  &de_DE,
  &es_ES,
  &gl_ES,
  &ca_ES,
  &ko_KR,
};

struct strings *l10n = &en_US;
