// Do not edit this file! It is automatically generated!

#include "en-US/strings.h"
#include "fr-FR/strings.h"
#include "pl-PL/strings.h"
#include "pt-BR/strings.h"
#include "sk-SK/strings.h"
#include "ru-RU/strings.h"
#include "zh-CN/strings.h"
#include "it-IT/strings.h"
#include "de-DE/strings.h"
#include "es-ES/strings.h"
#include "gl-ES/strings.h"

struct strings *languages[] = {
	&en_US,
	&fr_FR,
	&pl_PL,
	&pt_BR,
	&sk_SK,
	&ru_RU,
	&zh_CN,
	&it_IT,
	&de_DE,
	&es_ES,
	&gl_ES,
};

struct strings *l10n = &en_US;
